// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// entropies
NumericVector entropies(DataFrame data, IntegerVector classes, List patternPool);
RcppExport SEXP _ORAND_entropies(SEXP dataSEXP, SEXP classesSEXP, SEXP patternPoolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type classes(classesSEXP);
    Rcpp::traits::input_parameter< List >::type patternPool(patternPoolSEXP);
    rcpp_result_gen = Rcpp::wrap(entropies(data, classes, patternPool));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP f4r_fpgrowth(SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ORAND_entropies", (DL_FUNC) &_ORAND_entropies, 3},
    {"f4r_fpgrowth",     (DL_FUNC) &f4r_fpgrowth,     4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ORAND(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
