# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the patterns impurity scores
#'
#' @param data data
#' @param classes classes
#' @param patternPool patterns to get the scores for
NULL

impurityScores <- function(data, rClasses, patternPool, rMetric) {
    .Call('_ORAND_impurityScores', PACKAGE = 'ORAND', data, rClasses, patternPool, rMetric)
}

