# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the pattern conditional entropies
#'
#' @param data data
#' @param classes classes
#' @param patternPool patterns to get entropies for
NULL

entropies <- function(data, classes, patternPool) {
    .Call('_ORAND_entropies', PACKAGE = 'ORAND', data, classes, patternPool)
}

